
INSERT INTO country values 
	(SELECT SEQ_COUNTRY.NEXTVAL FROM DUAL, 'BR'),
	(SELECT SEQ_COUNTRY.NEXTVAL FROM DUAL, 'GB'),
	(SELECT SEQ_COUNTRY.NEXTVAL FROM DUAL, 'US');

INSERT INTO proposal VALUES (SELECT SEQ_PROPOSAL.NEXTVAL FROM DUAL, 'STANDARD PROPOSAL');

INSERT INTO service VALUES (SELECT SEQ_SERVICE.NEXTVAL FROM DUAL, 'Service One', SELECT SEQ_PROPOSAL.CURRVAL FROM DUAL, 5);
INSERT INTO service VALUES (SELECT SEQ_SERVICE.NEXTVAL FROM DUAL, 'Service Two', SELECT SEQ_PROPOSAL.CURRVAL FROM DUAL, 11);